#base	"../_extras/_customizations/transparent_viewmodels/transparent_viewmodels.res"
#base   "../../cfg/hudfixes/hud_killfeed.txt"
#base	"../_extras/scripts/hudlayout.res"
#base	"../_fixes/scripts/hudlayout.res"
#base	"../_tf2hud/scripts/hudlayout.res"